MOCK_BACKEND: http://localhost:1080

local:
  server:
    port: 8080

spring:
  reactor:
    context-propagation: auto
  cloud:
    gateway:
      routes:
        - id: answer_route
          uri: ${MOCK_BACKEND}
          predicates:
            - Path=/question-route
            - Method=GET
          filters:
            - RewritePath=/question-route, /question

logging:
  level:
    org.mockserver: WARN
    org.springframework.security: WARN
    org.springframework.cloud.gateway: WARN
#    reactor.netty.http.client: DEBUG
#    reactor.netty.http.server: DEBUG
