MOCK_BACKEND: http://localhost:1080

local:
  server:
    port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: answer_route
          uri: ${MOCK_BACKEND}
          predicates:
            - Path=/question-route
            - Method=GET
          filters:
            - RewritePath=/question-route, /question

  sleuth:
    enabled: true
    propagation:
      type: b3,w3c
    reactor:
      instrumentation-type: decorate_queues

logbook:
  filter.enabled: true
  format.style: http

logging:
  level:
    org.mockserver: WARN
    org.org.springframework.security: WARN
    org.springframework.cloud.gateway: WARN
    org.zalando.logbook: TRACE
#    reactor.netty.http.client: DEBUG
#    reactor.netty.http.server: DEBUG
