name: Build

on:
  push:

jobs:
  build-branch:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          overwrite-settings: false

      - name: Run tests
        run: ./gradlew clean test --info --stacktrace --no-daemon
